language: java
jdk:
    - oraclejdk8
install: true
script: mvn clean install --activate-profiles check --quiet --batch-mode
notifications:
  irc:
    channels:
      - "chat.freenode.net#52north"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: false
